/* eslint-disable eslint-comments/no-unlimited-disable */

/* eslint-disable */

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/~__root'
import { Route as IndexImport } from './routes/~index'
import { Route as FighterIndexImport } from './routes/~fighter/~$id/~index.y
import { Route as AttendanceIndexImport } from './routes/~attendance/~index'

// Create Virtual Routes

const FighterIdIndexLazyImport = createFileRoute('/fighter/$id/')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FighterIndexRoute = FighterIndexImport.update({
  id: '/fighter/',
  path: '/fighter/',
  getParentRoute: () => rootRoute,
} as any)

const AttendanceIndexRoute = AttendanceIndexImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => rootRoute,
} as any)

const FighterIdIndexLazyRoute = FighterIdIndexLazyImport.update({
  id: '/fighter/$id/',
  path: '/fighter/$id/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/~fighter/~$id/~index').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/attendance/': {
      id: '/attendance/'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceIndexImport
      parentRoute: typeof rootRoute
    }
    '/fighter/': {
      id: '/fighter/'
      path: '/fighter'
      fullPath: '/fighter'
      preLoaderRoute: typeof FighterIndexImport
      parentRoute: typeof rootRoute
    }
    '/fighter/$id/': {
      id: '/fighter/$id/'
      path: '/fighter/$id'
      fullPath: '/fighter/$id'
      preLoaderRoute: typeof FighterIdIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceIndexRoute
  '/fighter': typeof FighterIndexRoute
  '/fighter/$id': typeof FighterIdIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceIndexRoute
  '/fighter': typeof FighterIndexRoute
  '/fighter/$id': typeof FighterIdIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/attendance/': typeof AttendanceIndexRoute
  '/fighter/': typeof FighterIndexRoute
  '/fighter/$id/': typeof FighterIdIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/attendance' | '/fighter' | '/fighter/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/attendance' | '/fighter' | '/fighter/$id'
  id: '__root__' | '/' | '/attendance/' | '/fighter/' | '/fighter/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceIndexRoute: typeof AttendanceIndexRoute
  FighterIndexRoute: typeof FighterIndexRoute
  FighterIdIndexLazyRoute: typeof FighterIdIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceIndexRoute: AttendanceIndexRoute,
  FighterIndexRoute: FighterIndexRoute,
  FighterIdIndexLazyRoute: FighterIdIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "~__root.tsx",
      "children": [
        "/",
        "/attendance/",
        "/fighter/",
        "/fighter/$id/"
      ]
    },
    "/": {
      "filePath": "~index.tsx"
    },
    "/attendance/": {
      "filePath": "~attendance/~index.tsx"
    },
    "/fighter/": {
      "filePath": "~fighter/~index.tsx"
    },
    "/fighter/$id/": {
      "filePath": "~fighter/~$id/~index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
