/* eslint-disable eslint-comments/no-unlimited-disable */

/* eslint-disable */

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/~__root'
import { Route as appRouteImport } from './routes/~(app)/~route'
import { Route as AuthRegisterImport } from './routes/~auth/~register'
import { Route as appHomeImport } from './routes/~(app)/~home'
import { Route as AdminIndexImport } from './routes/~admin/~index'
import { Route as appSerializedGearCheckImport } from './routes/~(app)/~serialized-gear/~check'
import { Route as appSerializedGearIndexImport } from './routes/~(app)/~serialized-gear/~index'
import { Route as appFighterIndexImport } from './routes/~(app)/~fighter/~index'
import { Route as appAttendanceIndexImport } from './routes/~(app)/~attendance/~index'
import { Route as appFighterIdIndexImport } from './routes/~(app)/~fighter/~$id/~index'
import { Route as appAttendanceReportsIndexImport } from './routes/~(app)/~attendance/~reports/~index'
import { Route as appAttendanceDailyIndexImport } from './routes/~(app)/~attendance/~daily/~index'

// Create Virtual Routes

const Import = createFileRoute('/')()

// Create/Update Routes

const appRouteRoute = appRouteImport.update({
  id: '/(app)',
  getParentRoute: () => Route,
} as any)

const Route = Import.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any)

const appHomeRoute = appHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => appRouteRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any)

const appSerializedGearCheckRoute = appSerializedGearCheckImport.update({
  id: '/serialized-gear/check',
  path: '/serialized-gear/check',
  getParentRoute: () => appRouteRoute,
} as any)

const appSerializedGearIndexRoute = appSerializedGearIndexImport.update({
  id: '/serialized-gear/',
  path: '/serialized-gear/',
  getParentRoute: () => appRouteRoute,
} as any)

const appFighterIndexRoute = appFighterIndexImport.update({
  id: '/fighter/',
  path: '/fighter/',
  getParentRoute: () => appRouteRoute,
} as any)

const appAttendanceIndexRoute = appAttendanceIndexImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => appRouteRoute,
} as any)

const appFighterIdIndexRoute = appFighterIdIndexImport.update({
  id: '/fighter/$id/',
  path: '/fighter/$id/',
  getParentRoute: () => appRouteRoute,
} as any)

const appAttendanceReportsIndexRoute = appAttendanceReportsIndexImport.update({
  id: '/attendance/reports/',
  path: '/attendance/reports/',
  getParentRoute: () => appRouteRoute,
} as any)

const appAttendanceDailyIndexRoute = appAttendanceDailyIndexImport.update({
  id: '/attendance/daily/',
  path: '/attendance/daily/',
  getParentRoute: () => appRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof Import
      parentRoute: typeof rootRoute
    }
    '/(app)': {
      id: '/(app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appRouteImport
      parentRoute: typeof Route
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof rootRoute
    }
    '/(app)/home': {
      id: '/(app)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof appHomeImport
      parentRoute: typeof appRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/(app)/attendance/': {
      id: '/(app)/attendance/'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof appAttendanceIndexImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/fighter/': {
      id: '/(app)/fighter/'
      path: '/fighter'
      fullPath: '/fighter'
      preLoaderRoute: typeof appFighterIndexImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/serialized-gear/': {
      id: '/(app)/serialized-gear/'
      path: '/serialized-gear'
      fullPath: '/serialized-gear'
      preLoaderRoute: typeof appSerializedGearIndexImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/serialized-gear/check': {
      id: '/(app)/serialized-gear/check'
      path: '/serialized-gear/check'
      fullPath: '/serialized-gear/check'
      preLoaderRoute: typeof appSerializedGearCheckImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/attendance/daily/': {
      id: '/(app)/attendance/daily/'
      path: '/attendance/daily'
      fullPath: '/attendance/daily'
      preLoaderRoute: typeof appAttendanceDailyIndexImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/attendance/reports/': {
      id: '/(app)/attendance/reports/'
      path: '/attendance/reports'
      fullPath: '/attendance/reports'
      preLoaderRoute: typeof appAttendanceReportsIndexImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/fighter/$id/': {
      id: '/(app)/fighter/$id/'
      path: '/fighter/$id'
      fullPath: '/fighter/$id'
      preLoaderRoute: typeof appFighterIdIndexImport
      parentRoute: typeof appRouteImport
    }
  }
}

// Create and export the route tree

interface appRouteRouteChildren {
  appHomeRoute: typeof appHomeRoute
  appAttendanceIndexRoute: typeof appAttendanceIndexRoute
  appFighterIndexRoute: typeof appFighterIndexRoute
  appSerializedGearIndexRoute: typeof appSerializedGearIndexRoute
  appSerializedGearCheckRoute: typeof appSerializedGearCheckRoute
  appAttendanceDailyIndexRoute: typeof appAttendanceDailyIndexRoute
  appAttendanceReportsIndexRoute: typeof appAttendanceReportsIndexRoute
  appFighterIdIndexRoute: typeof appFighterIdIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appHomeRoute: appHomeRoute,
  appAttendanceIndexRoute: appAttendanceIndexRoute,
  appFighterIndexRoute: appFighterIndexRoute,
  appSerializedGearIndexRoute: appSerializedGearIndexRoute,
  appSerializedGearCheckRoute: appSerializedGearCheckRoute,
  appAttendanceDailyIndexRoute: appAttendanceDailyIndexRoute,
  appAttendanceReportsIndexRoute: appAttendanceReportsIndexRoute,
  appFighterIdIndexRoute: appFighterIdIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface RouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
}

const RouteChildren: RouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
}

const RouteWithChildren = Route._addFileChildren(RouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof appRouteRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/home': typeof appHomeRoute
  '/auth/register': typeof AuthRegisterRoute
  '/attendance': typeof appAttendanceIndexRoute
  '/fighter': typeof appFighterIndexRoute
  '/serialized-gear': typeof appSerializedGearIndexRoute
  '/serialized-gear/check': typeof appSerializedGearCheckRoute
  '/attendance/daily': typeof appAttendanceDailyIndexRoute
  '/attendance/reports': typeof appAttendanceReportsIndexRoute
  '/fighter/$id': typeof appFighterIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof appRouteRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/home': typeof appHomeRoute
  '/auth/register': typeof AuthRegisterRoute
  '/attendance': typeof appAttendanceIndexRoute
  '/fighter': typeof appFighterIndexRoute
  '/serialized-gear': typeof appSerializedGearIndexRoute
  '/serialized-gear/check': typeof appSerializedGearCheckRoute
  '/attendance/daily': typeof appAttendanceDailyIndexRoute
  '/attendance/reports': typeof appAttendanceReportsIndexRoute
  '/fighter/$id': typeof appFighterIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof RouteWithChildren
  '/(app)': typeof appRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/(app)/home': typeof appHomeRoute
  '/auth/register': typeof AuthRegisterRoute
  '/(app)/attendance/': typeof appAttendanceIndexRoute
  '/(app)/fighter/': typeof appFighterIndexRoute
  '/(app)/serialized-gear/': typeof appSerializedGearIndexRoute
  '/(app)/serialized-gear/check': typeof appSerializedGearCheckRoute
  '/(app)/attendance/daily/': typeof appAttendanceDailyIndexRoute
  '/(app)/attendance/reports/': typeof appAttendanceReportsIndexRoute
  '/(app)/fighter/$id/': typeof appFighterIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/home'
    | '/auth/register'
    | '/attendance'
    | '/fighter'
    | '/serialized-gear'
    | '/serialized-gear/check'
    | '/attendance/daily'
    | '/attendance/reports'
    | '/fighter/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/home'
    | '/auth/register'
    | '/attendance'
    | '/fighter'
    | '/serialized-gear'
    | '/serialized-gear/check'
    | '/attendance/daily'
    | '/attendance/reports'
    | '/fighter/$id'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/admin/'
    | '/(app)/home'
    | '/auth/register'
    | '/(app)/attendance/'
    | '/(app)/fighter/'
    | '/(app)/serialized-gear/'
    | '/(app)/serialized-gear/check'
    | '/(app)/attendance/daily/'
    | '/(app)/attendance/reports/'
    | '/(app)/fighter/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  Route: typeof RouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const rootRouteChildren: RootRouteChildren = {
  Route: RouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "~__root.tsx",
      "children": [
        "/",
        "/admin/",
        "/auth/register"
      ]
    },
    "/": {
      "filePath": "~(app)",
      "children": [
        "/(app)"
      ]
    },
    "/(app)": {
      "filePath": "~(app)/~route.tsx",
      "parent": "/",
      "children": [
        "/(app)/home",
        "/(app)/attendance/",
        "/(app)/fighter/",
        "/(app)/serialized-gear/",
        "/(app)/serialized-gear/check",
        "/(app)/attendance/daily/",
        "/(app)/attendance/reports/",
        "/(app)/fighter/$id/"
      ]
    },
    "/admin/": {
      "filePath": "~admin/~index.tsx"
    },
    "/(app)/home": {
      "filePath": "~(app)/~home.tsx",
      "parent": "/(app)"
    },
    "/auth/register": {
      "filePath": "~auth/~register.tsx"
    },
    "/(app)/attendance/": {
      "filePath": "~(app)/~attendance/~index.tsx",
      "parent": "/(app)"
    },
    "/(app)/fighter/": {
      "filePath": "~(app)/~fighter/~index.tsx",
      "parent": "/(app)"
    },
    "/(app)/serialized-gear/": {
      "filePath": "~(app)/~serialized-gear/~index.tsx",
      "parent": "/(app)"
    },
    "/(app)/serialized-gear/check": {
      "filePath": "~(app)/~serialized-gear/~check.tsx",
      "parent": "/(app)"
    },
    "/(app)/attendance/daily/": {
      "filePath": "~(app)/~attendance/~daily/~index.tsx",
      "parent": "/(app)"
    },
    "/(app)/attendance/reports/": {
      "filePath": "~(app)/~attendance/~reports/~index.tsx",
      "parent": "/(app)"
    },
    "/(app)/fighter/$id/": {
      "filePath": "~(app)/~fighter/~$id/~index.tsx",
      "parent": "/(app)"
    }
  }
}
ROUTE_MANIFEST_END */
